language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test BusinessLogic.Tests/BusinessLogic.Tests.csproj
 - dotnet test Models.Tests/Models.Tests.csproj