/*
Deployment script for Aquarium

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Aquarium"
:setvar DefaultFilePrefix "Aquarium"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Rename refactoring operation with key 93b35925-04cb-4d34-ad04-45d02a2edbea is skipped, element [dbo].[Aquariums].[ID] (SqlSimpleColumn) will not be renamed to Id';


GO
PRINT N'Rename refactoring operation with key 74d0871d-c596-4f9f-a4d0-72faa0c980f6 is skipped, element [dbo].[MeasurementTypes].[ID] (SqlSimpleColumn) will not be renamed to Id';


GO
PRINT N'Rename refactoring operation with key 40f4bfd4-03f1-4111-9e93-9e145cccfbdf is skipped, element [dbo].[Units].[ID] (SqlSimpleColumn) will not be renamed to Id';


GO
PRINT N'Rename refactoring operation with key 30ccab65-1311-4cd6-8b44-58c525d739d0 is skipped, element [dbo].[Measurements].[ID] (SqlSimpleColumn) will not be renamed to Id';


GO
PRINT N'Rename refactoring operation with key 69868238-6b9d-4487-847f-dafb17e189a7 is skipped, element [dbo].[Measurements].[MeasurementTypeID] (SqlSimpleColumn) will not be renamed to MeasurementTypeId';


GO
PRINT N'Rename refactoring operation with key 16625129-970a-4b4e-8257-36825d6bb532 is skipped, element [dbo].[Measurements].[UnitID] (SqlSimpleColumn) will not be renamed to UnitId';


GO
PRINT N'Rename refactoring operation with key df2c8022-a6d7-491e-956a-f607045aa259 is skipped, element [dbo].[Measurements].[AquariumID] (SqlSimpleColumn) will not be renamed to AquariumId';


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [Id]       INT          NOT NULL,
    [Username] VARCHAR (50) NOT NULL,
    [Password] VARCHAR (50) NOT NULL,
    [Hash]     VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '93b35925-04cb-4d34-ad04-45d02a2edbea')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('93b35925-04cb-4d34-ad04-45d02a2edbea')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '74d0871d-c596-4f9f-a4d0-72faa0c980f6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('74d0871d-c596-4f9f-a4d0-72faa0c980f6')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '40f4bfd4-03f1-4111-9e93-9e145cccfbdf')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('40f4bfd4-03f1-4111-9e93-9e145cccfbdf')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '30ccab65-1311-4cd6-8b44-58c525d739d0')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('30ccab65-1311-4cd6-8b44-58c525d739d0')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '69868238-6b9d-4487-847f-dafb17e189a7')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('69868238-6b9d-4487-847f-dafb17e189a7')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '16625129-970a-4b4e-8257-36825d6bb532')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('16625129-970a-4b4e-8257-36825d6bb532')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'df2c8022-a6d7-491e-956a-f607045aa259')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('df2c8022-a6d7-491e-956a-f607045aa259')

GO

GO
PRINT N'Update complete.';


GO
